### ISSUE TITLE
iOS Safari rendering

### ISSUE THREAD

**Issue by timurey** [ndrewtl/airspace-jekyll#10] opened 2017-05-14 11:29 UTC
In Safari browser on iPhone background image scale is not proper:
![img_3878](https://cloud.githubusercontent.com/assets/12942127/26033267/1dce4900-38c2-11e7-89e9-4b00da48aaf5.PNG)
But in desktop Chrome Browser it's look right:
![luminousrubyist github io-airspace-jekyll- iphone 6](https://cloud.githubusercontent.com/assets/12942127/26033266/1d9f532a-38c2-11e7-83a6-3fdfceb73388.png)

**Comment by ndrewtl** [comment] 2018-08-03 15:21
Apologies– I've looked into this repeatedly and truthfully have no idea why this is happening. You can contact the [original developers of this theme](https://themefisher.com/submit-ticket/) to figure out what's going on, but fixing a bug in the original template is outside the purview of this port. Given that the scope of the issue is relatively small (only one browser on only one platform), I'm closing this for now, but if you figure out the issue, I'd love to see a pull request fixing this.

Sorry, and good luck!

@ndrewtl

**Closed by ndrewtl** 2018-08-03 15:21 UTC
Labels: wontfix
